In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option('display.max_columns', None)

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/My Dataset/ml_olympaid/train.csv')
df.head()

,col_0,col_1,col_2,col_3,col_4,col_5,col_6,col_7,col_8,col_9,col_10,col_11,col_12,col_13,col_14,col_15,col_16,col_17,col_18,col_19,col_20,col_21,col_22,col_23,col_24,col_25,Amount,Class
0,-0.082423,-0.015885,0.018296,0.105834,0.291156,0.896142,0.416348,1.854701,-1.378885,-1.910856,0.604230,-1.075685,-0.061769,-0.433251,-2.607791,-0.326539,-0.059030,1.140944,-1.716960,-1.399815,0.146446,-1.442996,1.713633,-1.351671,-0.752007,0.174225,8.400,0
1,-0.134807,-0.038678,0.186766,0.061890,1.691469,-0.583866,0.022343,-1.261033,0.060611,1.567038,-0.744162,0.565000,-0.599505,NaN,-0.402509,0.954646,-0.169216,1.949623,0.881305,0.270719,0.200727,0.378079,-0.707367,0.005269,-0.234881,-0.129527,4.200,0
2,0.050357,0.043518,-0.084152,0.121125,1.782521,-0.614403,0.215234,-2.049707,0.018533,0.315355,-0.941150,-0.774718,3.003092,0.273515,1.689802,-1.662092,0.282405,1.831009,1.190881,1.210408,0.754548,1.155251,-0.154011,0.328052,-0.239821,-0.162559,146.958,0
3,0.104938,0.105659,0.441895,-0.272794,-2.273324,2.845803,-1.722852,1.520203,-2.716840,1.817746,1.575395,-0.252826,0.439894,-1.054180,NaN,-0.940693,0.331142,0.482808,1.097569,-0.682473,0.733577,NaN,0.557412,-0.793795,-0.459385,-0.893781,32.256,0
4,NaN,-0.194533,-0.022850,1.017750,0.062345,0.166484,NaN,1.358151,0.234661,1.516270,-1.218913,-0.112761,0.364553,-0.430106,2.085072,0.963968,0.776721,-0.470592,0.236036,1.172562,-1.397078,-1.231025,0.268283,-0.030406,0.258374,0.352570,982.800,0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 227845 entries, 0 to 227844
Data columns (total 28 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   col_0   216575 non-null  float64
 1   col_1   216487 non-null  float64
 2   col_2   216589 non-null  float64
 3   col_3   216329 non-null  float64
 4   col_4   216404 non-null  float64
 5   col_5   216432 non-null  float64
 6   col_6   216591 non-null  float64
 7   col_7   216303 non-null  float64
 8   col_8   216597 non-null  float64
 9   col_9   216570 non-null  float64
 10  col_10  216486 non-null  float64
 11  col_11  216626 non-null  float64
 12  col_12  216484 non-null  float64
 13  col_13  216509 non-null  float64
 14  col_14  216447 non-null  float64
 15  col_15  216511 non-null  float64
 16  col_16  216601 non-null  float64
 17  col_17  216478 non-null  float64
 18  col_18  216480 non-null  float64
 19  col_19  216395 non-null  float64
 20  col_20  216418 non-null  float64
 21  col_21  216694 non-null  float64
 22  col_22  216508 non-null  float64
 23  col_23  216532 non-null  float64
 24  col_24  216550 non-null  float64
 25  col_25  216478 non-null  float64
 26  Amount  216577 non-null  float64
 27  Class   227845 non-null  int64
dtypes: float64(27), int64(1)
memory usage: 48.7 MB

In [ ]:
df.shape

(227845, 28)

In [ ]:
df.isnull().sum()

col_0     11270
col_1     11358
col_2     11256
col_3     11516
col_4     11441
col_5     11413
col_6     11254
col_7     11542
col_8     11248
col_9     11275
col_10    11359
col_11    11219
col_12    11361
col_13    11336
col_14    11398
col_15    11334
col_16    11244
col_17    11367
col_18    11365
col_19    11450
col_20    11427
col_21    11151
col_22    11337
col_23    11313
col_24    11295
col_25    11367
Amount    11268
Class         0
dtype: int64

In [ ]:
df['Class'].value_counts()

0    227459
1       386
Name: Class, dtype: int64

In [ ]:
Class_df = pd.DataFrame(df.groupby('Class')['Class'].count())

p_0 = np.round((df.groupby('Class')['Class'].count()[0]/ df.shape[0]) * 100,2)
p_1 = np.round((df.groupby('Class')['Class'].count()[1]/ df.shape[0]) * 100,2)

Class_df.insert(loc = 0, column = "Distribution (%)", value = [p_0,p_1])
Class_df = Class_df[['Class', 'Distribution (%)']]
Class_df

        Class  Distribution (%)
Class
0      227459             99.83
1         386              0.17

In [ ]:
df.describe()

,col_0,col_1,col_2,col_3,col_4,col_5,col_6,col_7,col_8,col_9,col_10,col_11,col_12,col_13,col_14,col_15,col_16,col_17,col_18,col_19,col_20,col_21,col_22,col_23,col_24,col_25,Amount,Class
count,216575.000000,216487.000000,216589.000000,216329.000000,216404.000000,216432.000000,216591.000000,216303.000000,216597.000000,216570.000000,216486.000000,216626.000000,216484.000000,216509.000000,216447.000000,216511.000000,216601.000000,216478.000000,216480.000000,216395.000000,216418.000000,216694.000000,216508.000000,216532.000000,216550.000000,216478.000000,216577.000000,227845.000000
mean,0.000229,-0.000126,0.000331,-0.000525,-0.000526,-0.000158,-0.000102,-0.000078,-0.000227,-0.000132,-0.000060,0.000114,-0.000448,0.000329,-0.000576,0.000784,0.000779,-0.000570,-0.000040,-0.000327,-0.000466,-0.000228,0.000265,0.000636,0.000842,-0.000037,371.665017,0.001694
std,1.028109,1.018636,1.006971,1.010691,1.005785,1.004279,1.004137,1.003762,1.003388,1.001289,1.002382,1.001549,1.001340,1.000697,0.999450,0.999645,0.998935,0.999945,0.996764,0.997894,0.996585,0.987583,0.995828,0.992925,0.994308,0.991232,1066.320484,0.041125
min,-12.534818,-24.136023,-42.596932,-18.389573,-8.903645,-12.336780,-10.313776,-8.447604,-6.867517,-9.475184,-21.221886,-5.711499,-6.182575,-8.917440,-8.196965,-6.496993,-5.258195,-13.309702,-11.859792,-4.935091,-9.150431,-23.463300,-35.121227,-29.458874,-20.742471,-25.989995,0.000000,0.000000
25%,-0.201527,-0.242609,-0.234060,-0.378458,-0.666558,-0.552500,-0.422956,-0.625530,-0.466698,-0.632653,-0.568964,-0.612463,-0.671397,-0.590684,-0.604187,-0.646900,-0.668310,-0.610021,-0.613154,-0.695916,-0.550091,-0.636771,-0.526179,-0.626435,-0.351538,-0.316297,23.226000,0.000000
50%,-0.081197,-0.087972,-0.046638,-0.101950,-0.067947,-0.165624,0.093313,-0.011849,0.089351,0.026454,0.004856,0.063294,-0.004802,0.021564,0.030166,0.031959,-0.004517,0.010518,-0.025704,-0.112756,0.039346,-0.039562,0.038656,-0.049468,0.007527,-0.041073,92.400000,0.000000
75%,0.038132,0.059179,0.220770,0.218991,0.562910,0.305342,0.607992,0.550563,0.536848,0.674867,0.588616,0.688738,0.644899,0.611272,0.615761,0.674890,0.638935,0.580465,0.583021,0.608280,0.584253,0.593386,0.597012,0.575796,0.371850,0.214929,323.736000,0.000000
max,82.800134,103.568785,60.457531,65.706061,10.092467,23.183412,16.777160,18.520812,11.513192,12.589335,21.353217,22.930514,6.741260,23.696243,8.651819,7.635043,6.030460,30.482006,32.717865,8.669287,12.534569,20.253393,42.800066,15.799010,29.857560,116.634298,107902.872000,1.000000

In [ ]:
def downcast(df):
    cols = df.dtypes.index.tolist()
    types = df.dtypes.values.tolist()
    for i, t in enumerate(types):
        if 'int' in str(t):
            if (df[cols[i]].min() > np.iinfo(np.int8).min) and (df[cols[i]].max() < np.iinfo(np.int8).max):
                df[cols[i]] = df[cols[i]].astype(np.int8)
                
            elif (df[cols[i]].min() > np.iinfo(np.int16).min) and (df[cols[i]].max() < np.iinfo(np.int16).max):
                df[cols[i]] = df[cols[i]].astype(np.int16)
                
            elif (df[cols[i]].min() > np.iinfo(np.int32).min) and (df[cols[i]].max() < np.iinfo(np.int32).max):
                df[cols[i]] = df[cols[i]].astype(np.int32)
            
            else:
                df[cols[i]] = df[cols[i]].asypes(np.int64)
        elif 'float' in str(t):
            if (df[cols[i]].min() > np.finfo(np.float16).min) and (df[cols[i]].max() < np.finfo(np.float16).max):
                df[cols[i]] = df[cols[i]].astype(np.float16)
                
            elif (df[cols[i]].min() > np.finfo(np.float32).min) and (df[cols[i]].max() < np.finfo(np.float32).max):
                df[cols[i]] = df[cols[i]].astype(np.float32)
            
            else:
                df[cols[i]] = df[cols[i]].asypes(np.float64)
        elif t == object:
            if cols[i] == 'date':
                #df[cols[i]] = pd.to_datetime(df[cols[i]], format = '%Y-%m-%d')
                pass
            else:
                df[cols[i]] = df[cols[i]].astypes('category')
    return df

In [ ]:
print('\nDataFrame Size: {} mb'.format(np.round(df.memory_usage().sum()/(1024*1024),1)))

DataFrame Size: 48.7 mb

In [ ]:
df = downcast(df)
print('DataFrame Size: {} mb'.format(np.round(df.memory_usage().sum()/(1024*1024),1)))

DataFrame Size: 12.4 mb

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 227845 entries, 0 to 227844
Data columns (total 28 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   col_0   216575 non-null  float16
 1   col_1   216487 non-null  float16
 2   col_2   216589 non-null  float16
 3   col_3   216329 non-null  float16
 4   col_4   216404 non-null  float16
 5   col_5   216432 non-null  float16
 6   col_6   216591 non-null  float16
 7   col_7   216303 non-null  float16
 8   col_8   216597 non-null  float16
 9   col_9   216570 non-null  float16
 10  col_10  216486 non-null  float16
 11  col_11  216626 non-null  float16
 12  col_12  216484 non-null  float16
 13  col_13  216509 non-null  float16
 14  col_14  216447 non-null  float16
 15  col_15  216511 non-null  float16
 16  col_16  216601 non-null  float16
 17  col_17  216478 non-null  float16
 18  col_18  216480 non-null  float16
 19  col_19  216395 non-null  float16
 20  col_20  216418 non-null  float16
 21  col_21  216694 non-null  float16
 22  col_22  216508 non-null  float16
 23  col_23  216532 non-null  float16
 24  col_24  216550 non-null  float16
 25  col_25  216478 non-null  float16
 26  Amount  216577 non-null  float32
 27  Class   227845 non-null  int8
dtypes: float16(26), float32(1), int8(1)
memory usage: 12.4 MB

In [ ]:
df.to_csv('/content/drive/MyDrive/My Dataset/ml_olympaid/train_downcast.csv', index = False)